DROP TABLE IF EXISTS PRODUCTOS;
DROP TABLE IF EXISTS HISTORICO;
DROP trigger IF EXISTS AUDIT_PRODUCTOS;
create table HISTORICO (IDH INT AUTO_INCREMENT NOT NULL, NUEVOPRECIO INT NOT NULL, ANTIGUOPRECIO INT, FECHA datetime, CONSTRAINT PKH PRIMARY KEY (IDH));
create table PRODUCTOS (IDP INT AUTO_INCREMENT NOT NULL, PRECIO INT, CONSTRAINT PKP PRIMARY KEY (IDP));

DELIMITER //
CREATE TRIGGER AUDIT_PRODUCTOS
BEFORE UPDATE ON PRODUCTOS
FOR EACH ROW  
BEGIN
	 IF NEW.PRECIO>OLD.PRECIO THEN
		INSERT INTO HISTORICO (NUEVOPRECIO, ANTIGUOPRECIO, FECHA) VALUES (NEW.PRECIO, OLD.PRECIO, now());
	END IF;
END;
//
DELIMITER ;

insert into PRODUCTOS (PRECIO) Values (100);
insert into PRODUCTOS (PRECIO) values (200);
insert into PRODUCTOS (PRECIO)  values (300);
UPDATE PRODUCTOS SET PRECIO=PRECIO+200 WHERE IDP>1;
select * from HISTORICO;
